### ISSUE TITLE
herokuでswiper-bundle.cssが読み込まれない

### ISSUE THREAD

**Issue by HrkNishimura** [HrkNishimura/cinemat#115]
# 実現したいこと
herokuで`swiper-bundle.css`が読み込まれるようにしたいです。

# 現状発生している問題
ローカルでは問題なく読み込めているのですが、herokuだと`swiper-bundle.js`は読み込めているのですが、`swiper-bundle.css`が読み込めていません。

## ▼ローカル
[![Image from Gyazo](https://i.gyazo.com/fbb6a645e21e0969d455ee661b90f5fb.png)](https://gyazo.com/fbb6a645e21e0969d455ee661b90f5fb)

## ▼heroku
[![Image from Gyazo](https://i.gyazo.com/ca75fcb7115a0a2e092ca7474f43395b.jpg)](https://gyazo.com/ca75fcb7115a0a2e092ca7474f43395b)

# 該当のソースコード
- `swiper-bundle.css`を読み込んでいる記述
https://github.com/HrkNishimura/cinemat/blob/044b736023/app/javascript/packs/swiper.js
```
# app/javascript/packs/swiper.js

import Swiper from 'swiper/swiper-bundle';
import 'swiper/swiper-bundle.css';

const swiper = new Swiper('.swiper', {
  loop: true,
  direction: 'vertical',
});
```

- `package.json`
https://github.com/HrkNishimura/cinemat/blob/044b736023cded770ccbc2e697764e19e72d793c/package.json
```
# package.json

{
  "name": "cinemat",
  "private": true,
  "dependencies": {
    "@fortawesome/fontawesome-free": "^5.15.4",
    "@popperjs/core": "^2.10.2",
    "@rails/actioncable": "^6.0.0",
    "@rails/activestorage": "^6.0.0",
    "@rails/ujs": "^6.0.0",
    "@rails/webpacker": "5.4.3",
    "bootstrap": "^5.1.3",
    "jquery": "^3.6.0",
    "popper.js": "^1.16.1",
    "swiper": "^7.0.8",
    "turbolinks": "^5.2.0",
    "webpack": "^4.46.0",
    "webpack-cli": "^3.3.12"
  },
  "version": "0.1.0",
  "devDependencies": {
    "webpack-dev-server": "^3"
  }
}
```

- `webpack.config.js`
作成していません

# 考えられる原因
画像に赤い矢印がありますが、ローカルだと読み込まれている`css-loader`が、herokuだと読み込まれていません。
なので、`css-loader`が読み込まれていないことに原因があるのではないかと考えました。

# 試したこと
- `css-loader`と`style-loader`を`npm install`
- `package.json`で`node.js`のバージョン指定
- `webpack.config.js`の作成

`package.json`
https://github.com/HrkNishimura/cinemat/blob/master/package.json
```
# package.json

{
  "name": "cinemat",
  "private": true,
  "version": "0.1.0",
  "engines": {
    "node": "15.14.0"
  },
  "dependencies": {
    "@fortawesome/fontawesome-free": "^5.15.4",
    "@popperjs/core": "^2.10.2",
    "@rails/actioncable": "^6.0.0",
    "@rails/activestorage": "^6.0.0",
    "@rails/ujs": "^6.0.0",
    "@rails/webpacker": "5.4.3",
    "bootstrap": "^5.1.3",
    "jquery": "^3.6.0",
    "popper.js": "^1.16.1",
    "swiper": "^7.2.0",
    "turbolinks": "^5.2.0",
    "webpack": "^4.46.0",
    "webpack-cli": "^3.3.12"
  },
  "devDependencies": {
    "css-loader": "^5.2.7",
    "style-loader": "^2.0.0",
    "webpack-dev-server": "^3"
  }
}
```

`webpack.config.js`
https://github.com/HrkNishimura/cinemat/blob/master/webpack.config.js
```
# webpack.config.js

module.exports = {
  module: {
    rules: [
      {
        test: /node_modules\/(.+)\.css$/,
        use: [
          {
            loader: 'style-loader',
          },
          {
            loader: 'css-loader',
            options: {
              sourceMap: IS_DEVS,
            },
          },
        ],
        sideEffects: true
      }
    ]
  }
}
```

上記の変更を行い、herokuにデプロイを試みたところ、以下のエラーが発生してデプロイができませんでした。

# 現状発生している問題・エラーメッセージ

```
% git push heroku master
Enumerating objects: 17, done.
Counting objects: 100% (17/17), done.
Delta compression using up to 8 threads
Compressing objects: 100% (14/14), done.
Writing objects: 100% (14/14), 4.63 KiB | 1.16 MiB/s, done.
Total 14 (delta 7), reused 0 (delta 0), pack-reused 0
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Building on the Heroku-20 stack
remote: -----> Using buildpacks:
remote:        1. heroku/nodejs
remote:        2. heroku/ruby
remote: -----> Node.js app detected
remote:        
remote: -----> Creating runtime environment
remote:        
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        USE_YARN_CACHE=true
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:        
remote: -----> Installing binaries
remote:        engines.node (package.json):  15.14.0
remote:        engines.npm (package.json):   unspecified (use default)
remote:        engines.yarn (package.json):  unspecified (use default)
remote:        
remote:        Resolving node version 15.14.0...
remote:        Downloading and installing node 15.14.0...
remote:        Using default npm version: 7.7.6
remote:        Resolving yarn version 1.22.x...
remote:        Downloading and installing yarn (1.22.17)
remote:        Installed yarn 1.22.17
remote:        
remote: -----> Restoring cache
remote:        - yarn cache
remote:        
remote: -----> Installing dependencies
remote:        Installing node modules (yarn.lock)
remote:        yarn install v1.22.17
remote:        [1/4] Resolving packages...
remote:        [2/4] Fetching packages...
remote:        [3/4] Linking dependencies...
remote:        [4/4] Building fresh packages...
remote:        Done in 12.39s.
remote:        
remote: -----> Build
remote:        
remote: -----> Pruning devDependencies
remote:        yarn install v1.22.17
remote:        [1/4] Resolving packages...
remote:        [2/4] Fetching packages...
remote:        [3/4] Linking dependencies...
remote:        [4/4] Building fresh packages...
remote:        warning Ignored scripts due to flag.
remote:        Done in 5.47s.
remote:        
remote: -----> Caching build
remote:        - yarn cache
remote:        
remote: -----> Build succeeded!
remote:  !     This app may not specify any way to start a node process
remote:        https://devcenter.heroku.com/articles/nodejs-support#default-web-process-type
remote: 
remote: -----> Ruby app detected
remote: -----> Installing bundler 2.2.21
remote: -----> Removing BUNDLED WITH version in the Gemfile.lock
remote: -----> Compiling Ruby/Rails
remote: -----> Using Ruby version: ruby-3.0.2
remote: -----> Installing dependencies using bundler 2.2.21
remote:        Running: BUNDLE_WITHOUT='development:test' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4
remote:        Using rake 13.0.6
remote:        Using concurrent-ruby 1.1.9
remote:        Using i18n 1.8.10
remote:        Using minitest 5.14.4
remote:        Using thread_safe 0.3.6
remote:        Using tzinfo 1.2.9
remote:        Using zeitwerk 2.5.1
remote:        Using activesupport 6.0.3.7
remote:        Using builder 3.2.4
remote:        Using erubi 1.10.0
remote:        Using racc 1.6.0
remote:        Using nokogiri 1.12.5 (x86_64-linux)
remote:        Using rails-dom-testing 2.0.3
remote:        Using crass 1.0.6
remote:        Using loofah 2.12.0
remote:        Using rails-html-sanitizer 1.4.2
remote:        Using actionview 6.0.3.7
remote:        Using rack 2.2.3
remote:        Using rack-test 1.1.0
remote:        Using actionpack 6.0.3.7
remote:        Using nio4r 2.5.8
remote:        Using websocket-extensions 0.1.5
remote:        Using websocket-driver 0.7.5
remote:        Using actioncable 6.0.3.7
remote:        Using globalid 0.5.2
remote:        Using activejob 6.0.3.7
remote:        Using activemodel 6.0.3.7
remote:        Using activerecord 6.0.3.7
remote:        Using marcel 1.0.2
remote:        Using activestorage 6.0.3.7
remote:        Using mini_mime 1.1.2
remote:        Using mail 2.7.1
remote:        Using actionmailbox 6.0.3.7
remote:        Using actionmailer 6.0.3.7
remote:        Using actiontext 6.0.3.7
remote:        Using public_suffix 4.0.6
remote:        Using addressable 2.8.0
remote:        Using bcrypt 3.1.16
remote:        Using msgpack 1.4.2
remote:        Using bootsnap 1.8.1
remote:        Using bundler 2.2.22
remote:        Using mini_magick 4.11.0
remote:        Using ffi 1.15.4
remote:        Using ruby-vips 2.1.3
remote:        Using image_processing 1.12.1
remote:        Using ssrf_filter 1.0.7
remote:        Using carrierwave 2.2.2
remote:        Using deep_merge 1.2.1
remote:        Using dry-core 0.7.1
remote:        Using dry-configurable 0.13.0
remote:        Using dry-container 0.9.0
remote:        Using dry-initializer 3.0.4
remote:        Using dry-logic 1.2.0
remote:        Using dry-inflector 0.2.1
remote:        Using dry-types 1.5.1
remote:        Using dry-schema 1.8.0
remote:        Using dry-validation 1.7.0
remote:        Using config 2.2.3
remote:        Using unf_ext 0.0.8
remote:        Using unf 0.1.4
remote:        Using domain_name 0.5.20190701
remote:        Using dotenv 2.7.6
remote:        Using method_source 1.0.0
remote:        Using thor 1.1.0
remote:        Using railties 6.0.3.7
remote:        Using dotenv-rails 2.7.6
remote:        Using excon 0.87.0
remote:        Using faraday-em_http 1.0.0
remote:        Using faraday-em_synchrony 1.0.0
remote:        Using faraday-excon 1.1.0
remote:        Using faraday-httpclient 1.0.1
remote:        Using faraday-net_http 1.0.1
remote:        Using faraday-net_http_persistent 1.2.0
remote:        Using faraday-patron 1.0.0
remote:        Using faraday-rack 1.0.0
remote:        Using multipart-post 2.1.1
remote:        Using ruby2_keywords 0.0.5
remote:        Using faraday 1.8.0
remote:        Using formatador 0.3.0
remote:        Using mime-types-data 3.2021.0901
remote:        Using mime-types 3.3.1
remote:        Using fog-core 2.2.4
remote:        Using multi_json 1.15.0
remote:        Using fog-json 1.2.0
remote:        Using fog-xml 0.1.4
remote:        Using ipaddress 0.8.3
remote:        Using fog-aws 3.9.0
remote:        Using high_voltage 3.1.2
remote:        Using http-accept 1.7.0
remote:        Using http-cookie 1.0.4
remote:        Using jbuilder 2.11.2
remote:        Using rexml 3.2.4
remote:        Using scanf 1.0.0
remote:        Using jpmobile 6.1.1
remote:        Using jquery-rails 4.3.5
remote:        Using jwt 2.3.0
remote:        Using mimemagic 0.4.3
remote:        Using multi_xml 0.6.0
remote:        Using netrc 0.11.0
remote:        Using oauth 0.5.6
remote:        Using oauth2 1.4.7
remote:        Using pagy 4.11.0
remote:        Using pg 1.1.4
remote:        Using polyamorous 2.3.2
remote:        Using puma 3.12.6
remote:        Using rack-proxy 0.7.0
remote:        Using sprockets 4.0.2
remote:        Using sprockets-rails 3.2.2
remote:        Using rails 6.0.3.7
remote:        Using rails-i18n 6.0.0
remote:        Using ransack 2.3.2
remote:        Using rest-client 2.1.0
remote:        Using sassc 2.4.0
remote:        Using tilt 2.0.10
remote:        Using sassc-rails 2.1.2
remote:        Using sass-rails 6.0.0
remote:        Using semantic_range 3.0.0
remote:        Using simple_form 5.1.0
remote:        Using sorcery 0.16.1
remote:        Using themoviedb-api 1.3.0
remote:        Using turbolinks-source 5.2.0
remote:        Using turbolinks 5.2.1
remote:        Using webpacker 5.4.3
remote:        Bundle complete! 39 Gemfile dependencies, 123 gems now installed.
remote:        Gems in the groups 'development' and 'test' were not installed.
remote:        Bundled gems are installed into `./vendor/bundle`
remote:        Bundle completed (0.67s)
remote:        Cleaning up the bundler cache.
remote:        Removing bundler (2.2.21)
remote: -----> Detecting rake tasks
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        yarn install v1.22.17
remote:        [1/5] Validating package.json...
remote:        [2/5] Resolving packages...
remote:        [3/5] Fetching packages...
remote:        [4/5] Linking dependencies...
remote:        [5/5] Building fresh packages...
remote:        Done in 27.41s.
remote:        Warning: you are using an unstable release of Node.js (v15.14.0). If you encounter issues with Node.js, consider switching to an Active LTS release. More info: https://docs.npmjs.com/try-the-latest-stable-version-of-node
remote:        Compiling...
remote:        Compilation failed:
remote:        ModuleNotFoundError: Module not found: Error: Can't resolve 'css-loader' in '/tmp/build_cf3cfa52'
remote:            at /tmp/build_cf3cfa52/node_modules/webpack/lib/Compilation.js:925:10
remote:            at /tmp/build_cf3cfa52/node_modules/webpack/lib/NormalModuleFactory.js:401:22
remote:            at /tmp/build_cf3cfa52/node_modules/webpack/lib/NormalModuleFactory.js:130:21
remote:            at /tmp/build_cf3cfa52/node_modules/webpack/lib/NormalModuleFactory.js:337:24
remote:            at /tmp/build_cf3cfa52/node_modules/neo-async/async.js:2830:7
remote:            at /tmp/build_cf3cfa52/node_modules/neo-async/async.js:6877:13
remote:            at /tmp/build_cf3cfa52/node_modules/neo-async/async.js:2830:7
remote:            at done (/tmp/build_cf3cfa52/node_modules/neo-async/async.js:2925:13)
remote:            at /tmp/build_cf3cfa52/node_modules/webpack/lib/NormalModuleFactory.js:449:23
remote:            at /tmp/build_cf3cfa52/node_modules/enhanced-resolve/lib/Resolver.js:213:14
remote:            at /tmp/build_cf3cfa52/node_modules/enhanced-resolve/lib/Resolver.js:285:5
remote:            at eval (eval at create (/tmp/build_cf3cfa52/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
remote:            at /tmp/build_cf3cfa52/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
remote:            at /tmp/build_cf3cfa52/node_modules/enhanced-resolve/lib/Resolver.js:285:5
remote:            at eval (eval at create (/tmp/build_cf3cfa52/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
remote:            at /tmp/build_cf3cfa52/node_modules/enhanced-resolve/lib/Resolver.js:285:5
remote:            at eval (eval at create (/tmp/build_cf3cfa52/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
remote:            at /tmp/build_cf3cfa52/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
remote:            at /tmp/build_cf3cfa52/node_modules/enhanced-resolve/lib/Resolver.js:285:5
remote:            at eval (eval at create (/tmp/build_cf3cfa52/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
remote:            at /tmp/build_cf3cfa52/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:30:40
remote:            at /tmp/build_cf3cfa52/node_modules/enhanced-resolve/lib/Resolver.js:285:5
remote:            at eval (eval at create (/tmp/build_cf3cfa52/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
remote:            at /tmp/build_cf3cfa52/node_modules/enhanced-resolve/lib/Resolver.js:285:5
remote:            at eval (eval at create (/tmp/build_cf3cfa52/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
remote:            at /tmp/build_cf3cfa52/node_modules/enhanced-resolve/lib/forEachBail.js:30:14
remote:            at /tmp/build_cf3cfa52/node_modules/enhanced-resolve/lib/Resolver.js:285:5
remote:            at eval (eval at create (/tmp/build_cf3cfa52/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
remote:            at /tmp/build_cf3cfa52/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
remote:            at /tmp/build_cf3cfa52/node_modules/enhanced-resolve/lib/Resolver.js:285:5
remote:            at eval (eval at create (/tmp/build_cf3cfa52/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
remote:            at /tmp/build_cf3cfa52/node_modules/enhanced-resolve/lib/Resolver.js:285:5
remote:            at eval (eval at create (/tmp/build_cf3cfa52/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
remote:            at /tmp/build_cf3cfa52/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
remote:            at /tmp/build_cf3cfa52/node_modules/enhanced-resolve/lib/Resolver.js:285:5
remote:            at eval (eval at create (/tmp/build_cf3cfa52/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
remote:        resolve 'css-loader' in '/tmp/build_cf3cfa52'
remote:          Parsed request is a module
remote:          using description file: /tmp/build_cf3cfa52/package.json (relative path: .)
remote:            resolve as module
remote:              /tmp/node_modules doesn't exist or is not a directory
remote:              /node_modules doesn't exist or is not a directory
remote:              looking for modules in /tmp/build_cf3cfa52/node_modules
remote:                using description file: /tmp/build_cf3cfa52/package.json (relative path: ./node_modules)
remote:                  using description file: /tmp/build_cf3cfa52/package.json (relative path: ./node_modules/css-loader)
remote:                    no extension
remote:                      /tmp/build_cf3cfa52/node_modules/css-loader doesn't exist
remote:                    .js
remote:                      /tmp/build_cf3cfa52/node_modules/css-loader.js doesn't exist
remote:                    .json
remote:                      /tmp/build_cf3cfa52/node_modules/css-loader.json doesn't exist
remote:                    as directory
remote:                      /tmp/build_cf3cfa52/node_modules/css-loader doesn't exist
remote:        
remote: 
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !       Push rejected to stormy-escarpment-40061.
remote: 
To https://git.heroku.com/stormy-escarpment-40061.git
 ! [remote rejected]   master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/stormy-escarpment-40061.git'
```
# エラーから考えられる原因
`ModuleNotFoundError: Module not found: Error: Can't resolve 'css-loader' in '/tmp/build_cf3cfa52'`の記述を見つけ、このエラーメッセージで検索し、以下のような対応を行いました。

# 試したこと
- `npm install css-loader -D`コマンドの入力
参考：https://stackoverflow.com/questions/51890932/module-not-found-error-cant-resolve-css-loader?rq=1
- `/src/index.js`、`/src/style.css`ファイルの作成
参考：https://ics.media/entry/17376/
- `webpack.config.js`に`sideEffects: true`の記述を追加
参考：https://www.serendip.ws/archives/6398

これらを試したのですが、`ModuleNotFoundError: Module not found: Error: Can't resolve 'css-loader' in '/tmp/build_cf3cfa52'`のエラーが変わらず表示されました。

8時間くらい試行錯誤したのですが、解決できなかったので、質問のご依頼をさせていただきました。
ご回答いただけますと幸いです。

**Comment by murata0705** [comment]
@HrkNishimura 
今環境構築中ですが、`app/javascript/packs/swiper.js` こちら、ドキュメントだと下記の様に読み込んでますけど、下記でもだめですかね？

```js
// import Swiper bundle with all modules installed
import Swiper from 'swiper/bundle';

// import styles bundle
import 'swiper/css/bundle';

// init Swiper:
const swiper = new Swiper(...);

**Comment by murata0705** [comment]
試したことは一旦戻してもらった方がいいかもしれません。

- css-loaderとstyle-loaderをnpm install
- package.jsonでnode.jsのバージョン指定
- webpack.config.jsの作成

**Comment by murata0705** [comment]
https://mikamisan.hatenablog.com/entry/2017/09/10/171955

これのやり方の方が良い気がしますね。

**Comment by murata0705** [comment]
- css インポート削除

```app/javascript/packs/swiper.js
import Swiper from 'swiper/swiper-bundle';

const swiper = new Swiper('.swiper', {
  loop: true,
  direction: 'vertical',
});
```

- scss インポート

```app/javascript/src/application.scss
@import '~bootstrap/scss/bootstrap';
@import '~@fortawesome/fontawesome-free/scss/fontawesome';
@import 'swiper/swiper';
```

これでローカルで動けば行けそうな気がします。

**Comment by HrkNishimura** [comment]
@murata0705 
コメントいただきありがとうございます。
早速試してみますので、お待ちいただけますでしょうか。

**Comment by HrkNishimura** [comment]
@murata0705 
いただいた内容で、ローカルでもherokuでも、swiper-bundle.cssが無事読み込めました！
1つ目の内容で問題ありませんでした。

ご対応いただき、ありがとうございます・・・！
